### PR TITLE
Fix error response for unsupported transactions types.

### LINKED ISSUE #24: getSubmissionStatus returns incorrect error response on unsupported transaction type
**Bug Description**

The submissionStatus endpoint only supports transfers and account creations, this is documented and deliberate.
However if querying submission status of an unsupported transaction the response is 

```json
{"error":0,"errorMessage":"Cannot communicate with node via GRPC endpoint"}
```
which is incorrect. The error should be more precise and not misleading.

**Steps to Reproduce**

Query submissionStatus for an unsupported transaction type.

**Expected Result**

Get an error result indicating that the type is unsupported, and "InvalidRequest" status code.

**Actual Result**

Misleading error result and status code 502.

### PR DESCRIPTION
**Pull request by abizjak**
## Purpose

Fix regression introduced in #82 related to response status for unsupported transaction types.

Closes #24 

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

File: src/Proxy.hs [hunk 1]
```diff
@@ -897,29 +897,37 @@ putTransferR =
...
 
--- |Return a @ClientMonad@ which gets a "simple" status of the transaction with the given @TransactionHash@.
-getSimpleTransactionStatus :: MonadIO m => I18n -> TransactionHash -> ClientMonad m (GRPCResult (Either String Value))
+data OutcomeConversionError =
+  OCEError !String
+  | OCEUnsupportedType
+
+-- |Return a @ClientMonad@ which gets a "simple" status of the transaction with
+-- the given @TransactionHash@. If the transaction status is not for one of the
+-- supported transactions 'Nothing' is returned.
```
Comment (vikt0r0) [inline src/Proxy.hs:906]:
```suggestion
-- |Return a @ClientMonad@ which gets a "simple" status of the transaction with
-- the given @TransactionHash@. Note that it only supports a subset of transaction
-- types in the sense that @Nothing@ is returned iff the transaction is unsupported
-- and either committed or finalized.
```

**Review by vikt0r0 — APPROVED** [review]
Good find!

File: src/Proxy.hs [hunk 2]
```diff
@@ -897,29 +897,37 @@ putTransferR =
                 Left err -> fail err
                 Right tx -> return tx
 
--- |Return a @ClientMonad@ which gets a "simple" status of the transaction with the given @TransactionHash@.
-getSimpleTransactionStatus :: MonadIO m => I18n -> TransactionHash -> ClientMonad m (GRPCResult (Either String Value))
+data OutcomeConversionError =
```
[the remark this answers is not in the document]
Comment (abizjak) [reply src/Proxy.hs:902]: Added

File: src/Proxy.hs (hunk 1 above)
Comment (abizjak) [reply src/Proxy.hs:910]: I prefer my phrasing. :)
